composite -compose out Back.bmp 00.png PUZ00.png
composite -compose out Back.bmp 01.png PUZ01.png
composite -compose out Back.bmp 02.png PUZ02.png
composite -compose out Back.bmp 03.png PUZ03.png
composite -compose out Back.bmp 04.png PUZ04.png
composite -compose out Back.bmp 05.png PUZ05.png
composite -compose out Back.bmp 06.png PUZ06.png
composite -compose out Back.bmp 07.png PUZ07.png
composite -compose out Back.bmp 08.png PUZ08.png
composite -compose out Back.bmp 09.png PUZ09.png
composite -compose out Back.bmp 10.png PUZ10.png
composite -compose out Back.bmp 11.png PUZ11.png
composite -compose out Back.bmp 12.png PUZ12.png
composite -compose out Back.bmp 13.png PUZ13.png
composite -compose out Back.bmp 14.png PUZ14.png
composite -compose out Back.bmp 15.png PUZ15.png
composite -compose out Back.bmp 16.png PUZ16.png
composite -compose out Back.bmp 17.png PUZ17.png
composite -compose out Back.bmp 18.png PUZ18.png
composite -compose out Back.bmp 19.png PUZ19.png
composite -compose out Back.bmp 20.png PUZ20.png
composite -compose out Back.bmp 21.png PUZ21.png
composite -compose out Back.bmp 22.png PUZ22.png
composite -compose out Back.bmp 23.png PUZ23.png
composite -compose out Back.bmp 24.png PUZ24.png
composite -compose out Back.bmp 25.png PUZ25.png
composite -compose out Back.bmp 26.png PUZ26.png
composite -compose out Back.bmp 27.png PUZ27.png
composite -compose out Back.bmp 28.png PUZ28.png
composite -compose out Back.bmp 29.png PUZ29.png
composite -compose out Back.bmp 30.png PUZ30.png
composite -compose out Back.bmp 31.png PUZ31.png
composite -compose out Back.bmp 32.png PUZ32.png
composite -compose out Back.bmp 33.png PUZ33.png
composite -compose out Back.bmp 34.png PUZ34.png
composite -compose out Back.bmp 35.png PUZ35.png
composite -compose out Back.bmp 36.png PUZ36.png
composite -compose out Back.bmp 37.png PUZ37.png
composite -compose out Back.bmp 38.png PUZ38.png
composite -compose out Back.bmp 39.png PUZ39.png
composite -compose out Back.bmp 40.png PUZ40.png
composite -compose out Back.bmp 41.png PUZ41.png
composite -compose out Back.bmp 42.png PUZ42.png
composite -compose out Back.bmp 43.png PUZ43.png
composite -compose out Back.bmp 44.png PUZ44.png
composite -compose out Back.bmp 45.png PUZ45.png
composite -compose out Back.bmp 46.png PUZ46.png
composite -compose out Back.bmp 47.png PUZ47.png
